name: Test on pull request

on:
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with dotnet
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test
